name: Greengage Reusable JIT Tests on GitHub

# Environment variables
env:
  COMPOSE_HTTP_TIMEOUT: 400
  DOCKER_COMPOSE: "docker compose"

# Trigger for reusable workflow
on:
  workflow_call:
    inputs:
      version:
        description: 'Greengage version (e.g., 6 or 7)'
        required: true
        type: string
      target_os:
        description: 'Target OS (e.g., ubuntu)'
        type: string
      target_os_version:
        description: 'Target OS version (e.g., 24.04)'
        required: false
        type: string
        default: ''
      python3:
        description: 'Python3 build argument (ignored)'
        required: false
        type: string
        default: ''
    secrets:
      ghcr_token:
        description: 'GitHub token for GHCR access'
        required: true

jobs:
  optimizer:  # JIT tests
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        optimizer: [orca, postgres]
    permissions:
      contents: read  # Explicit for default behavior
      packages: read  # Explicit for GHCR access clarity
      actions: write  # Required for cache and artifact upload
    steps:
      - name: Maximize disk space
        uses: greengagedb/greengage-ci/.github/actions/maximize-disk-space@v19

      - name: Enable Docker IPv6
        uses: greengagedb/greengage-ci/.github/actions/enable-docker-ipv6@v51

      - name: Restore & Load SHA image
        uses: greengagedb/greengage-ci/.github/actions/restore-load-image@v25
        with:
          version: ${{ inputs.version }}
          target_os: ${{ inputs.target_os }}
          target_os_version: ${{ inputs.target_os_version }}

      # Checkout repository with shallow clone
      - name: Checkout Greengage repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          submodules: recursive

      # Run JIT tests
      - name: JIT test ${{ github.job }} ${{ matrix.optimizer }}
        env:
          ARCH: 'x86-64'
          IMAGE: ghcr.io/${{ github.repository }}/ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }}:${{ github.sha }}
          LOG_NAME: 'jit_ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }}_${{ matrix.optimizer }}'
        run: |
          export IMAGE=${IMAGE,,}

          docker run --name $LOG_NAME \
            -v /mnt/logs:/logs \
            -e TEST_OS='${{ inputs.target_os }}' \
            -e MAKE_TEST_COMMAND="-k PGOPTIONS='-c jit=on -c optimizer=${{ matrix.optimizer == 'orca' && 'on -c optimizer_jit_above_cost=0' || 'off' }} -c jit_above_cost=0 -c gp_explain_jit=off' installcheck" \
            --sysctl 'kernel.sem=500 1024000 200 4096' \
            $IMAGE \
            /bin/bash /home/gpadmin/gpdb_src/concourse/scripts/ic_gpdb.bash

      - name: Collect logs ${{ github.job }} ${{ matrix.optimizer }}
        if: always()
        uses: greengagedb/greengage-ci/.github/actions/collect-logs@v55
        with:
          log_path_prefix: jit_ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }}_${{ matrix.optimizer }}

     # Upload JIT artifacts
      - name: Upload JIT ${{ github.job }} ${{ matrix.optimizer }} artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jit_ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }}_${{ matrix.optimizer }}
          path: /mnt/logs
          retention-days: 7
          if-no-files-found: warn  # Warning if no artifacts are found
